[package]
name = "wyn-observatory-ui"
version = "0.1.2"
edition = "2024"
description = "Desktop fleet observability interface for WynObserve"

[[bin]]
name = "wynobserve"
path = "src/main.rs"

[dependencies]
eframe = "0.36.1"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
toml = "1.1.5"
wyn-protocol = { workspace = true }
reqwest = {
    version = "0.13",
    default-features = false,
    features = [
        "blocking",
        "json",
        "rustls",
    ]
}

semver = "1"

[package.metadata.deb]
name = "wynobserve"
maintainer = "QtumWyn <Qtummechanic25@gmail.com>"
section = "utils"
priority = "optional"
depends = "$auto, pkexec"

assets = [
    [
        "target/release/wynobserve",
        "usr/bin/wynobserve",
        "755"
    ],
    [
        "debian/wynobserve.desktop",
        "usr/share/applications/wynobserve.desktop",
        "644"
    ],
    [
        "config/prod.toml",
        "etc/wyncommand/observatory-prod.toml",
        "644"
    ],
]