use std::{
    env, fs,
    io::{self, Write},
    path::PathBuf,
};

use eframe::egui::Color32;

use crate::theme::{self, ThemePalette};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThemePreset {
    Gothic,
    Pastel,
    Cyberpunk,
    Custom,
}

impl ThemePreset {
    pub const ALL: [Self; 4] = [Self::Gothic, Self::Pastel, Self::Cyberpunk, Self::Custom];

    pub const fn label(self) -> &'static str {
        match self {
            Self::Gothic => "Gothic",
            Self::Pastel => "Pastel Dusk",
            Self::Cyberpunk => "Cyberpunk",
            Self::Custom => "Custom",
        }
    }

    fn key(self) -> &'static str {
        match self {
            Self::Gothic => "gothic",
            Self::Pastel => "pastel",
            Self::Cyberpunk => "cyberpunk",
            Self::Custom => "custom",
        }
    }

    fn parse(value: &str) -> Option<Self> {
        match value.trim().to_ascii_lowercase().as_str() {
            "gothic" => Some(Self::Gothic),
            "pastel" | "pastel_dusk" => Some(Self::Pastel),
            "cyberpunk" => Some(Self::Cyberpunk),
            "custom" => Some(Self::Custom),
            _ => None,
        }
    }
}

#[derive(Debug, Clone)]
pub struct UiPreferences {
    pub title: String,

    // Independent toggles on purpose. Wyn can be Catgirl + Batgirl,
    // while Eevee can be Bunnygirl and Val can be Puppygirl.
    pub catgirl: bool,
    pub batgirl: bool,
    pub bunnygirl: bool,
    pub puppygirl: bool,

    pub theme: ThemePreset,
    pub custom_theme: ThemePalette,
}

impl Default for UiPreferences {
    fn default() -> Self {
        Self {
            title: "WynCommand // Observatory".to_string(),
            catgirl: true,
            batgirl: true,
            bunnygirl: false,
            puppygirl: false,
            theme: ThemePreset::Gothic,
            custom_theme: theme::gothic_palette(),
        }
    }
}

impl UiPreferences {
    pub fn load() -> Self {
        let path = config_path();
        let Ok(contents) = fs::read_to_string(path) else {
            return Self::default();
        };

        let mut prefs = Self::default();

        for raw_line in contents.lines() {
            let line = raw_line.trim();

            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            let Some((key, value)) = line.split_once('=') else {
                continue;
            };

            let key = key.trim();
            let value = value.trim();

            match key {
                "title" => prefs.title = unescape_text(value),
                "catgirl" => prefs.catgirl = parse_bool(value, prefs.catgirl),
                "batgirl" => prefs.batgirl = parse_bool(value, prefs.batgirl),
                "bunnygirl" => prefs.bunnygirl = parse_bool(value, prefs.bunnygirl),
                "puppygirl" => prefs.puppygirl = parse_bool(value, prefs.puppygirl),
                "theme" => {
                    if let Some(theme) = ThemePreset::parse(value) {
                        prefs.theme = theme;
                    }
                }

                "custom_bg" => parse_color_into(value, &mut prefs.custom_theme.bg),
                "custom_panel" => parse_color_into(value, &mut prefs.custom_theme.panel),
                "custom_panel_alt" => parse_color_into(value, &mut prefs.custom_theme.panel_alt),
                "custom_border" => parse_color_into(value, &mut prefs.custom_theme.border),
                "custom_text" => parse_color_into(value, &mut prefs.custom_theme.text),
                "custom_muted" => parse_color_into(value, &mut prefs.custom_theme.muted),
                "custom_selection" => parse_color_into(value, &mut prefs.custom_theme.selection),
                "custom_primary" => parse_color_into(value, &mut prefs.custom_theme.primary),
                "custom_secondary" => parse_color_into(value, &mut prefs.custom_theme.secondary),
                "custom_info" => parse_color_into(value, &mut prefs.custom_theme.info),
                "custom_success" => parse_color_into(value, &mut prefs.custom_theme.success),
                "custom_warning" => parse_color_into(value, &mut prefs.custom_theme.warning),
                "custom_bright" => parse_color_into(value, &mut prefs.custom_theme.bright),
                _ => {}
            }
        }

        prefs
    }

    pub fn save(&self) -> io::Result<PathBuf> {
        let path = config_path();

        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }

        let mut file = fs::File::create(&path)?;

        writeln!(
            file,
            "# WynCommand Observatory UI preferences\n# Generated by the in-app customizer."
        )?;

        writeln!(file, "title={}", escape_text(&self.title))?;
        writeln!(file, "catgirl={}", self.catgirl)?;
        writeln!(file, "batgirl={}", self.batgirl)?;
        writeln!(file, "bunnygirl={}", self.bunnygirl)?;
        writeln!(file, "puppygirl={}", self.puppygirl)?;
        writeln!(file, "theme={}", self.theme.key())?;

        write_color(&mut file, "custom_bg", self.custom_theme.bg)?;
        write_color(&mut file, "custom_panel", self.custom_theme.panel)?;
        write_color(&mut file, "custom_panel_alt", self.custom_theme.panel_alt)?;
        write_color(&mut file, "custom_border", self.custom_theme.border)?;
        write_color(&mut file, "custom_text", self.custom_theme.text)?;
        write_color(&mut file, "custom_muted", self.custom_theme.muted)?;
        write_color(&mut file, "custom_selection", self.custom_theme.selection)?;
        write_color(&mut file, "custom_primary", self.custom_theme.primary)?;
        write_color(&mut file, "custom_secondary", self.custom_theme.secondary)?;
        write_color(&mut file, "custom_info", self.custom_theme.info)?;
        write_color(&mut file, "custom_success", self.custom_theme.success)?;
        write_color(&mut file, "custom_warning", self.custom_theme.warning)?;
        write_color(&mut file, "custom_bright", self.custom_theme.bright)?;

        Ok(path)
    }

    pub fn familiar_signature(&self) -> String {
        let mut familiars = Vec::new();

        if self.catgirl {
            familiars.push("catgirl");
        }

        if self.batgirl {
            familiars.push("batgirl");
        }

        if self.bunnygirl {
            familiars.push("bunnygirl");
        }

        if self.puppygirl {
            familiars.push("puppygirl");
        }

        familiars.join(" + ")
    }
}

pub fn config_path() -> PathBuf {
    config_base_dir()
        .join("wyncommand-observatory")
        .join("ui.conf")
}

#[cfg(target_os = "windows")]
fn config_base_dir() -> PathBuf {
    env::var_os("APPDATA")
        .map(PathBuf::from)
        .or_else(|| {
            env::var_os("USERPROFILE")
                .map(PathBuf::from)
                .map(|home| home.join("AppData").join("Roaming"))
        })
        .unwrap_or_else(|| PathBuf::from("."))
}

#[cfg(not(target_os = "windows"))]
fn config_base_dir() -> PathBuf {
    env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| {
            env::var_os("HOME")
                .map(PathBuf::from)
                .map(|home| home.join(".config"))
        })
        .unwrap_or_else(|| PathBuf::from("."))
}

fn parse_bool(value: &str, fallback: bool) -> bool {
    match value.trim().to_ascii_lowercase().as_str() {
        "true" | "1" | "yes" | "on" => true,
        "false" | "0" | "no" | "off" => false,
        _ => fallback,
    }
}

fn escape_text(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('\n', "\\n")
        .replace('\r', "")
}

fn unescape_text(value: &str) -> String {
    let mut output = String::new();
    let mut chars = value.chars();

    while let Some(ch) = chars.next() {
        if ch == '\\' {
            match chars.next() {
                Some('n') => output.push('\n'),
                Some('\\') => output.push('\\'),
                Some(other) => {
                    output.push('\\');
                    output.push(other);
                }
                None => output.push('\\'),
            }
        } else {
            output.push(ch);
        }
    }

    output
}

fn color_hex(color: Color32) -> String {
    format!(
        "#{:02X}{:02X}{:02X}{:02X}",
        color.r(),
        color.g(),
        color.b(),
        color.a()
    )
}

fn parse_color(value: &str) -> Option<Color32> {
    let hex = value.trim().trim_start_matches('#');

    match hex.len() {
        6 => {
            let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
            let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
            let b = u8::from_str_radix(&hex[4..6], 16).ok()?;

            Some(Color32::from_rgb(r, g, b))
        }
        8 => {
            let r = u8::from_str_radix(&hex[0..2], 16).ok()?;
            let g = u8::from_str_radix(&hex[2..4], 16).ok()?;
            let b = u8::from_str_radix(&hex[4..6], 16).ok()?;
            let a = u8::from_str_radix(&hex[6..8], 16).ok()?;

            Some(Color32::from_rgba_unmultiplied(r, g, b, a))
        }
        _ => None,
    }
}

fn parse_color_into(value: &str, target: &mut Color32) {
    if let Some(color) = parse_color(value) {
        *target = color;
    }
}

fn write_color(file: &mut fs::File, key: &str, color: Color32) -> io::Result<()> {
    writeln!(file, "{key}={}", color_hex(color))
}
