[package]
name = "wyncommand-agent"
version = "0.1.1"
edition = "2024"
description = "Distributed system telemetry agent for WynCommand Fleet"

[[bin]]
name = "wyn-agent"
path = "src/main.rs"

[dependencies]
sysinfo = "0.39.6"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1"
nvml-wrapper = "0.13"
libc = "0.2"
wyn-protocol = { workspace = true }
toml = "1.1.5"
iced-x86 = "1.21.0"

[target.'cfg(target_os = "linux")'.dependencies]
perf-event-open-sys = "6.0.0"

[build-dependencies]
cc = "1"

[package.metadata.deb]
name = "wyncommand-agent"
section = "utils"
priority = "optional"
depends = "$auto"

maintainer-scripts = "debian"

assets = [
    [
        "target/release/wyn-agent",
        "usr/bin/wyn-agent",
        "755"
    ],
    [
        "deploy/linux/wyn-agent-setup",
        "usr/bin/wyn-agent-setup",
        "755"
    ],
]

[package.metadata.deb.systemd-units]
unit-name = "wyn-agent"
enable = false
start = false
restart-after-upgrade = true