name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test WynObserve
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nasm

      - name: Update Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check workspace
        run: cargo check --workspace --locked

      - name: Test workspace
        run: cargo test --workspace --locked

      - name: Build workspace
        run: cargo build --workspace --release --locked
